version: "2"

services:
  master:
    image: docker.pkg.github.com/reitermarkus/parallel-systems/alpine-mpich:onbuild
    user: root
    entrypoint: ["mpi_bootstrap", "role=master", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - ./project:/project
    networks:
      - net

  worker:
    image: docker.pkg.github.com/reitermarkus/parallel-systems/alpine-mpich:onbuild
    user: root
    entrypoint: ["mpi_bootstrap", "role=worker", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]
    networks:
      - net

networks:
  net:
